//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.LABURNUM.COM
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicYearTable
    {
        public AcademicYearTable()
        {
            this.StudentFees = new HashSet<StudentFee>();
            this.StudentFeeDetails = new HashSet<StudentFeeDetail>();
        }
    
        public long AcademicYearTableId { get; set; }
        public string AcademicYear { get; set; }
        public int StartYear { get; set; }
        public int EndYear { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    
        public virtual ICollection<StudentFee> StudentFees { get; set; }
        public virtual ICollection<StudentFeeDetail> StudentFeeDetails { get; set; }
    }
}
