//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.LABURNUM.COM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public Album()
        {
            this.AlbumDetails = new HashSet<AlbumDetail>();
        }
    
        public long AlbumId { get; set; }
        public string AlbumName { get; set; }
        public string AlbumCoverImage { get; set; }
        public long AddedById { get; set; }
        public Nullable<long> UpdatedById { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    
        public virtual Faculty Faculty { get; set; }
        public virtual Faculty Faculty1 { get; set; }
        public virtual ICollection<AlbumDetail> AlbumDetails { get; set; }
    }
}
