//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.LABURNUM.COM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LaburnumEntities : DbContext
    {
        public LaburnumEntities()
            : base("name=LaburnumEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AcademicYearTable> AcademicYearTables { get; set; }
        public DbSet<AdmissionType> AdmissionTypes { get; set; }
        public DbSet<ApiClient> ApiClients { get; set; }
        public DbSet<AttendanceClass1> AttendanceClass1 { get; set; }
        public DbSet<AttendanceClass10> AttendanceClass10 { get; set; }
        public DbSet<AttendanceClass11> AttendanceClass11 { get; set; }
        public DbSet<AttendanceClass12> AttendanceClass12 { get; set; }
        public DbSet<AttendanceClass2> AttendanceClass2 { get; set; }
        public DbSet<AttendanceClass3> AttendanceClass3 { get; set; }
        public DbSet<AttendanceClass4> AttendanceClass4 { get; set; }
        public DbSet<AttendanceClass5> AttendanceClass5 { get; set; }
        public DbSet<AttendanceClass6> AttendanceClass6 { get; set; }
        public DbSet<AttendanceClass7> AttendanceClass7 { get; set; }
        public DbSet<AttendanceClass8> AttendanceClass8 { get; set; }
        public DbSet<AttendanceClass9> AttendanceClass9 { get; set; }
        public DbSet<AttendanceClassLKG> AttendanceClassLKGs { get; set; }
        public DbSet<AttendanceClassPreNursery> AttendanceClassPreNurseries { get; set; }
        public DbSet<AttendanceClassUKG> AttendanceClassUKGs { get; set; }
        public DbSet<Bank> Banks { get; set; }
        public DbSet<BusRoute> BusRoutes { get; set; }
        public DbSet<ChequeStatusMaster> ChequeStatusMasters { get; set; }
        public DbSet<Circular> Circulars { get; set; }
        public DbSet<CircularNotificationTable> CircularNotificationTables { get; set; }
        public DbSet<CircularNotificationTracker> CircularNotificationTrackers { get; set; }
        public DbSet<Class> Classes { get; set; }
        public DbSet<ClassSubjectFacultyTable> ClassSubjectFacultyTables { get; set; }
        public DbSet<ContactFormTable> ContactFormTables { get; set; }
        public DbSet<Faculty> Faculties { get; set; }
        public DbSet<Fee> Fees { get; set; }
        public DbSet<HomeWork> HomeWork { get; set; }
        public DbSet<LateFeePaneltyMaster> LateFeePaneltyMasters { get; set; }
        public DbSet<LoginActivity> LoginActivities { get; set; }
        public DbSet<Month> Months { get; set; }
        public DbSet<Salutation> Salutations { get; set; }
        public DbSet<Section> Sections { get; set; }
        public DbSet<Student> Students { get; set; }
        public DbSet<StudentFee> StudentFees { get; set; }
        public DbSet<StudentFeeDetail> StudentFeeDetails { get; set; }
        public DbSet<Subject> Subjects { get; set; }
        public DbSet<UserType> UserTypes { get; set; }
    }
}
