//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.LABURNUM.COM
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentFeeDetail
    {
        public long StudentFeeDetailId { get; set; }
        public long StudentId { get; set; }
        public long ClassId { get; set; }
        public long SectionId { get; set; }
        public double MonthlyFee { get; set; }
        public double LateFee { get; set; }
        public Nullable<double> TransportFee { get; set; }
        public Nullable<double> AnnualFunctionFee { get; set; }
        public Nullable<double> PendingFee { get; set; }
        public long PayForTheMonth { get; set; }
        public double DiscountAmount { get; set; }
        public string DiscountRemarks { get; set; }
        public long CollectedById { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Faculty Faculty { get; set; }
        public virtual Month Month { get; set; }
        public virtual Section Section { get; set; }
        public virtual Student Student { get; set; }
    }
}
