//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.LABURNUM.COM
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserType
    {
        public UserType()
        {
            this.Faculties = new HashSet<Faculty>();
            this.LoginActivities = new HashSet<LoginActivity>();
        }
    
        public long UserTypeId { get; set; }
        public string Text { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual ICollection<Faculty> Faculties { get; set; }
        public virtual ICollection<LoginActivity> LoginActivities { get; set; }
    }
}
